http:
  ipv4_host: '0.0.0.0' # all interfaces
  ipv6_host: '::' # all interfaces
  port: 8080

  trusted_proxies: []

  tracing:
    enabled: false
    otlp_endpoint: ''

  pprof:
    enabled: false

  metrics:
    enabled: false
    ipv4_host: '127.0.0.1' # localhost
    ipv6_host: '::1' # localhost
    port: 8081

actions:
- match_common_labels:
    alertname: TrunkRecorderNoCalls
  match_group_labels:
    namespace: trunk-recorder
  action: rollout-restart-deployment
  options:
    deployment: trunk-recorder-app
    namespace: trunk-recorder
