// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type tracingShadow struct {
	Enabled      *bool   `json:"enabled"       toml:"enabled"       yaml:"enabled"`
	OTLPEndpoint *string `json:"otlp_endpoint" toml:"otlp_endpoint" yaml:"otlp_endpoint"`
}

type pProfShadow struct {
	Enabled *bool `json:"enabled" toml:"enabled" yaml:"enabled"`
}

type metricsShadow struct {
	IPV4Host *string `json:"ipv4_host" toml:"ipv4_host" yaml:"ipv4_host"`
	IPV6Host *string `json:"ipv6_host" toml:"ipv6_host" yaml:"ipv6_host"`
	Port     *uint16 `json:"port"      toml:"port"      yaml:"port"`
	Enabled  *bool   `json:"enabled"   toml:"enabled"   yaml:"enabled"`
}

type hTTPShadow struct {
	IPV4Host                  *string        `json:"ipv4_host"       toml:"ipv4_host"       yaml:"ipv4_host"`
	IPV6Host                  *string        `json:"ipv6_host"       toml:"ipv6_host"       yaml:"ipv6_host"`
	Port                      *uint16        `json:"port"            toml:"port"            yaml:"port"`
	Tracing                   *tracingShadow `json:"tracing"         toml:"tracing"         yaml:"tracing"`
	PProf                     *pProfShadow   `json:"pprof"           toml:"pprof"           yaml:"pprof"`
	TrustedProxies            *[]string      `json:"trusted_proxies" toml:"trusted_proxies" yaml:"trusted_proxies"`
	Metrics                   *metricsShadow `json:"metrics"         toml:"metrics"         yaml:"metrics"`
	LegacyTracingEnabled      *bool          `json:"enabled"         toml:"enabled"         yaml:"enabled"`
	LegacyTracingOTLPEndpoint *string        `json:"otlp_endpoint"   toml:"otlp_endpoint"   yaml:"otlp_endpoint"`
}

type actionShadow struct {
	MatchCommonLabels *map[string]string `json:"match_common_labels" toml:"match_common_labels" yaml:"match_common_labels"`
	MatchGroupLabels  *map[string]string `json:"match_group_labels"  toml:"match_group_labels"  yaml:"match_group_labels"`
	Action            *string            `json:"action"              toml:"action"              yaml:"action"`
	Options           *map[string]string `json:"options"             toml:"options"             yaml:"options"`
}

type configShadow struct {
	HTTP    *hTTPShadow     `json:"http"    toml:"http"    yaml:"http"`
	Actions *[]actionShadow `json:"actions" toml:"actions" yaml:"actions"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}

func configApplyDefaults(cfg *Config, _ string, set configulator.SetOrigin) error {
	cfg.HTTP.IPV4Host = "0.0.0.0"
	set("http.ipv4_host", configulator.LayerDefault, "default tag")
	cfg.HTTP.IPV6Host = "::"
	set("http.ipv6_host", configulator.LayerDefault, "default tag")
	cfg.HTTP.Port = uint16(8080)
	set("http.port", configulator.LayerDefault, "default tag")
	cfg.HTTP.Tracing.Enabled = false
	set("http.tracing.enabled", configulator.LayerDefault, "default tag")
	cfg.HTTP.PProf.Enabled = false
	set("http.pprof.enabled", configulator.LayerDefault, "default tag")
	cfg.HTTP.Metrics.IPV4Host = "127.0.0.1"
	set("http.metrics.ipv4_host", configulator.LayerDefault, "default tag")
	cfg.HTTP.Metrics.IPV6Host = "::1"
	set("http.metrics.ipv6_host", configulator.LayerDefault, "default tag")
	cfg.HTTP.Metrics.Port = uint16(8081)
	set("http.metrics.port", configulator.LayerDefault, "default tag")
	cfg.HTTP.Metrics.Enabled = false
	set("http.metrics.enabled", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.HTTP != nil {
		if s.HTTP.IPV4Host != nil {
			cfg.HTTP.IPV4Host = *s.HTTP.IPV4Host
			set("http.ipv4_host", configulator.LayerFile, file)
		}
		if s.HTTP.IPV6Host != nil {
			cfg.HTTP.IPV6Host = *s.HTTP.IPV6Host
			set("http.ipv6_host", configulator.LayerFile, file)
		}
		if s.HTTP.Port != nil {
			cfg.HTTP.Port = *s.HTTP.Port
			set("http.port", configulator.LayerFile, file)
		}
		if s.HTTP.Tracing != nil {
			if s.HTTP.Tracing.Enabled != nil {
				cfg.HTTP.Tracing.Enabled = *s.HTTP.Tracing.Enabled
				set("http.tracing.enabled", configulator.LayerFile, file)
			}
			if s.HTTP.Tracing.OTLPEndpoint != nil {
				cfg.HTTP.Tracing.OTLPEndpoint = *s.HTTP.Tracing.OTLPEndpoint
				set("http.tracing.otlp_endpoint", configulator.LayerFile, file)
			}
		}
		if s.HTTP.PProf != nil {
			if s.HTTP.PProf.Enabled != nil {
				cfg.HTTP.PProf.Enabled = *s.HTTP.PProf.Enabled
				set("http.pprof.enabled", configulator.LayerFile, file)
			}
		}
		if s.HTTP.TrustedProxies != nil {
			cfg.HTTP.TrustedProxies = *s.HTTP.TrustedProxies
			set("http.trusted_proxies", configulator.LayerFile, file)
		}
		if s.HTTP.Metrics != nil {
			if s.HTTP.Metrics.IPV4Host != nil {
				cfg.HTTP.Metrics.IPV4Host = *s.HTTP.Metrics.IPV4Host
				set("http.metrics.ipv4_host", configulator.LayerFile, file)
			}
			if s.HTTP.Metrics.IPV6Host != nil {
				cfg.HTTP.Metrics.IPV6Host = *s.HTTP.Metrics.IPV6Host
				set("http.metrics.ipv6_host", configulator.LayerFile, file)
			}
			if s.HTTP.Metrics.Port != nil {
				cfg.HTTP.Metrics.Port = *s.HTTP.Metrics.Port
				set("http.metrics.port", configulator.LayerFile, file)
			}
			if s.HTTP.Metrics.Enabled != nil {
				cfg.HTTP.Metrics.Enabled = *s.HTTP.Metrics.Enabled
				set("http.metrics.enabled", configulator.LayerFile, file)
			}
		}
		if s.HTTP.LegacyTracingEnabled != nil {
			cfg.HTTP.LegacyTracingEnabled = *s.HTTP.LegacyTracingEnabled
			set("http.enabled", configulator.LayerFile, file)
		}
		if s.HTTP.LegacyTracingOTLPEndpoint != nil {
			cfg.HTTP.LegacyTracingOTLPEndpoint = *s.HTTP.LegacyTracingOTLPEndpoint
			set("http.otlp_endpoint", configulator.LayerFile, file)
		}
	}
	if s.Actions != nil {
		out := make([]Action, len(*s.Actions))
		for i, esh := range *s.Actions {
			var e Action
			idx := "actions[" + strconv.Itoa(i) + "]"
			if esh.MatchCommonLabels != nil {
				e.MatchCommonLabels = *esh.MatchCommonLabels
				set(idx+".match_common_labels", configulator.LayerFile, file)
			}
			if esh.MatchGroupLabels != nil {
				e.MatchGroupLabels = *esh.MatchGroupLabels
				set(idx+".match_group_labels", configulator.LayerFile, file)
			}
			if esh.Action != nil {
				e.Action = *esh.Action
				set(idx+".action", configulator.LayerFile, file)
			}
			if esh.Options != nil {
				e.Options = *esh.Options
				set(idx+".options", configulator.LayerFile, file)
			}
			out[i] = e
		}
		cfg.Actions = out
		set("actions", configulator.LayerFile, file)
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "ipv4_host"); ok {
		cfg.HTTP.IPV4Host = v
		set("http.ipv4_host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "ipv6_host"); ok {
		cfg.HTTP.IPV6Host = v
		set("http.ipv6_host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "port"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Port = uint16(p)
		set("http.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "tracing", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.tracing.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Tracing.Enabled = p
		set("http.tracing.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "tracing", "otlp_endpoint"); ok {
		cfg.HTTP.Tracing.OTLPEndpoint = v
		set("http.tracing.otlp_endpoint", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "pprof", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.pprof.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.PProf.Enabled = p
		set("http.pprof.enabled", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "trusted_proxies"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.HTTP.TrustedProxies = lst
		set("http.trusted_proxies", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "metrics", "ipv4_host"); ok {
		cfg.HTTP.Metrics.IPV4Host = v
		set("http.metrics.ipv4_host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "metrics", "ipv6_host"); ok {
		cfg.HTTP.Metrics.IPV6Host = v
		set("http.metrics.ipv6_host", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "metrics", "port"); ok {
		p, err := strconv.ParseUint(v, 10, 16)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.port",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Metrics.Port = uint16(p)
		set("http.metrics.port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "http", "metrics", "enabled"); ok {
		p, err := strconv.ParseBool(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.enabled",
				Source: n,
				Value:  v,
			}
		}
		cfg.HTTP.Metrics.Enabled = p
		set("http.metrics.enabled", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"http" + o.Separator + "ipv4_host",
		"http" + o.Separator + "ipv6_host",
		"http" + o.Separator + "port",
		"http" + o.Separator + "tracing" + o.Separator + "enabled",
		"http" + o.Separator + "tracing" + o.Separator + "otlp_endpoint",
		"http" + o.Separator + "pprof" + o.Separator + "enabled",
		"http" + o.Separator + "trusted_proxies",
		"http" + o.Separator + "metrics" + o.Separator + "ipv4_host",
		"http" + o.Separator + "metrics" + o.Separator + "ipv6_host",
		"http" + o.Separator + "metrics" + o.Separator + "port",
		"http" + o.Separator + "metrics" + o.Separator + "enabled",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "0.0.0.0", "HTTP server IPv4 host")
	fs.String(names[1], "::", "HTTP server IPv6 host")
	fs.Uint16(names[2], 8080, "HTTP server port")
	fs.Bool(names[3], false, "Enable OpenTelemetry tracing")
	fs.String(names[4], "", "OpenTelemetry OTLP endpoint")
	fs.Bool(names[5], false, "Enable pprof on the HTTP server")
	fs.StringSlice(names[6], nil, "Comma-separated list of trusted proxy IPs or CIDRs")
	fs.String(names[7], "127.0.0.1", "Metrics server IPv4 host")
	fs.String(names[8], "::1", "Metrics server IPv6 host")
	fs.Uint16(names[9], 8081, "Metrics server port")
	fs.Bool(names[10], false, "Enable the metrics server")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "http" + o.Separator + "ipv4_host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.ipv4_host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.IPV4Host = v
		set("http.ipv4_host", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "ipv6_host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.ipv6_host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.IPV6Host = v
		set("http.ipv6_host", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Port = v
		set("http.port", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "tracing" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.tracing.enabled",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Tracing.Enabled = v
		set("http.tracing.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "tracing" + o.Separator + "otlp_endpoint"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.tracing.otlp_endpoint",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Tracing.OTLPEndpoint = v
		set("http.tracing.otlp_endpoint", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "pprof" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.pprof.enabled",
				Source: "--" + n,
			}
		}
		cfg.HTTP.PProf.Enabled = v
		set("http.pprof.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "trusted_proxies"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.trusted_proxies",
				Source: "--" + n,
			}
		}
		cfg.HTTP.TrustedProxies = v
		set("http.trusted_proxies", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "metrics" + o.Separator + "ipv4_host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.ipv4_host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Metrics.IPV4Host = v
		set("http.metrics.ipv4_host", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "metrics" + o.Separator + "ipv6_host"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.ipv6_host",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Metrics.IPV6Host = v
		set("http.metrics.ipv6_host", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "metrics" + o.Separator + "port"; fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.port",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Metrics.Port = v
		set("http.metrics.port", configulator.LayerCLI, "--"+n)
	}
	if n := "http" + o.Separator + "metrics" + o.Separator + "enabled"; fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "http.metrics.enabled",
				Source: "--" + n,
			}
		}
		cfg.HTTP.Metrics.Enabled = v
		set("http.metrics.enabled", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "http":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("http", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub hTTPShadow
				if err := sub.decodeJSON(dec, "http"); err != nil {
					return err
				}
				s.HTTP = &sub
			}
		case "actions":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError("actions", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []actionShadow{}
				for dec.PeekKind() != jsontext.KindEndArray {
					ep := "actions" + "[" + strconv.Itoa(len(out)) + "]"
					et, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if et.Kind() != jsontext.KindBeginObject {
						return configJSONError(ep, et, fmt.Errorf("expected an object, got %v", et.Kind()))
					}
					var el actionShadow
					if err := el.decodeJSON(dec, ep); err != nil {
						return err
					}
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Actions = &out
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *hTTPShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "ipv4_host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.IPV4Host = &str
			default:
				return configJSONError(path+".ipv4_host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "ipv6_host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.IPV6Host = &str
			default:
				return configJSONError(path+".ipv6_host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw > math.MaxUint16 {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows uint16", raw))
				}
				num := uint16(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "tracing":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".tracing", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub tracingShadow
				if err := sub.decodeJSON(dec, path+".tracing"); err != nil {
					return err
				}
				s.Tracing = &sub
			}
		case "pprof":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".pprof", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub pProfShadow
				if err := sub.decodeJSON(dec, path+".pprof"); err != nil {
					return err
				}
				s.PProf = &sub
			}
		case "trusted_proxies":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError(path+".trusted_proxies", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".trusted_proxies"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.TrustedProxies = &out
			}
		case "metrics":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".metrics", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub metricsShadow
				if err := sub.decodeJSON(dec, path+".metrics"); err != nil {
					return err
				}
				s.Metrics = &sub
			}
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.LegacyTracingEnabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "otlp_endpoint":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.LegacyTracingOTLPEndpoint = &str
			default:
				return configJSONError(path+".otlp_endpoint", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *tracingShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		case "otlp_endpoint":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.OTLPEndpoint = &str
			default:
				return configJSONError(path+".otlp_endpoint", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *pProfShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *metricsShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "ipv4_host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.IPV4Host = &str
			default:
				return configJSONError(path+".ipv4_host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "ipv6_host":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.IPV6Host = &str
			default:
				return configJSONError(path+".ipv6_host", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Uint()
				if err != nil {
					return configJSONError(path+".port", v, err)
				}
				if raw > math.MaxUint16 {
					return configJSONError(path+".port", v, fmt.Errorf("%d overflows uint16", raw))
				}
				num := uint16(raw)
				s.Port = &num
			default:
				return configJSONError(path+".port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindTrue, jsontext.KindFalse:
				b := v.Bool()
				s.Enabled = &b
			default:
				return configJSONError(path+".enabled", v, fmt.Errorf("expected a bool, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *actionShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "match_common_labels":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".match_common_labels", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				out := map[string]string{}
				for dec.PeekKind() != jsontext.KindEndObject {
					kt, err := dec.ReadToken()
					if err != nil {
						return err
					}
					key := kt.String()
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".match_common_labels"+"."+configQuoteKey(key), v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out[key] = el
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.MatchCommonLabels = &out
			}
		case "match_group_labels":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".match_group_labels", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				out := map[string]string{}
				for dec.PeekKind() != jsontext.KindEndObject {
					kt, err := dec.ReadToken()
					if err != nil {
						return err
					}
					key := kt.String()
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".match_group_labels"+"."+configQuoteKey(key), v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out[key] = el
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.MatchGroupLabels = &out
			}
		case "action":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Action = &str
			default:
				return configJSONError(path+".action", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "options":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".options", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				out := map[string]string{}
				for dec.PeekKind() != jsontext.KindEndObject {
					kt, err := dec.ReadToken()
					if err != nil {
						return err
					}
					key := kt.String()
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".options"+"."+configQuoteKey(key), v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out[key] = el
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Options = &out
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// configJSONError returns a ParseError for the JSON token v at path.
func configJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "http.ipv4_host = %v\n", c.HTTP.IPV4Host)
	fmt.Fprintf(&b, "http.ipv6_host = %v\n", c.HTTP.IPV6Host)
	fmt.Fprintf(&b, "http.port = %v\n", c.HTTP.Port)
	fmt.Fprintf(&b, "http.tracing.enabled = %v\n", c.HTTP.Tracing.Enabled)
	fmt.Fprintf(&b, "http.tracing.otlp_endpoint = %v\n", c.HTTP.Tracing.OTLPEndpoint)
	fmt.Fprintf(&b, "http.pprof.enabled = %v\n", c.HTTP.PProf.Enabled)
	fmt.Fprintf(&b, "http.trusted_proxies = %v\n", c.HTTP.TrustedProxies)
	fmt.Fprintf(&b, "http.metrics.ipv4_host = %v\n", c.HTTP.Metrics.IPV4Host)
	fmt.Fprintf(&b, "http.metrics.ipv6_host = %v\n", c.HTTP.Metrics.IPV6Host)
	fmt.Fprintf(&b, "http.metrics.port = %v\n", c.HTTP.Metrics.Port)
	fmt.Fprintf(&b, "http.metrics.enabled = %v\n", c.HTTP.Metrics.Enabled)
	fmt.Fprintf(&b, "http.enabled = %v\n", c.HTTP.LegacyTracingEnabled)
	fmt.Fprintf(&b, "http.otlp_endpoint = %v\n", c.HTTP.LegacyTracingOTLPEndpoint)
	fmt.Fprintf(&b, "actions = %v\n", c.Actions)
	return b.String()
}

func configQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
